import React from "react";
const columns = [
  {name: "ID", uid: "id", sortable: true},
  {name: "NAME", uid: "name", sortable: true},
  {name: "AGE", uid: "age", sortable: true},
  {name: "ROLE", uid: "role", sortable: true},
  {name: "Date", uid: "date"},
  {name: "Grand Total", uid: "grand_total"},
  {name: "STATUS", uid: "status", sortable: true},
  {name: "ACTIONS", uid: "actions"},
];

const statusOptions = [
  {name: "Active", uid: "active"},
  {name: "Paused", uid: "paused"},
  {name: "Cancelled", uid: "cancelled"},
];

const users = [
  {
    id: 1,
    name: "บริษัท เอี่ยมศิริแป้งมัน จำกัด",
    role: "CEO",
    date: "วันจันทร์ ที่ 12 เดือน พฤศจิกายน 2566",
    status: "active",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    grand_total: "$ 7,029,000 3M",
  },
  {
    id: 2,
    name: "บริษัท แป้งมัน จำกัด",
    role: "Tech Lead",
    date: "วันจันทร์ ที่ 12 เดือน พฤศจิกายน 2566",
    status: "paused",
    age: "25",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    grand_total: "$ 7,029,000 3M",
  },
  {
    id: 3,
    name: "บริษัท เอี่ยมศิริ จำกัด",
    role: "Sr. Dev",
    date: "วันจันทร์ ที่ 12 เดือน พฤศจิกายน 2566",
    status: "active",
    age: "22",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    grand_total: "$ 7,029,000 3M",
  },
  {
    id: 4,
    name: "บริษัท ศิริแป้งมัน จำกัด",
    role: "C.M.",
    date: "วันจันทร์ ที่ 12 เดือน พฤศจิกายน 2566",
    status: "cancelled",
    age: "28",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    grand_total: "$ 7,029,000 3M",
  },
  {
    id: 5,
    name: "บริษัท เอี่ยมศิริแป้งมัน จำกัด",
    role: "S. Manager",
    date: "วันจันทร์ ที่ 12 เดือน พฤศจิกายน 2566",
    status: "active",
    age: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    grand_total: "$ 7,029,000 3M",
  },
  {
    id: 6,
    name: "Brian Kim",
    role: "P. Manager",
    date: "วันจันทร์ ที่ 12 เดือน พฤศจิกายน 2566",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    grand_total: "$ 7,029,000 3M",
    status: "Active",
  },
  {
    id: 7,
    name: "Michael Hunt",
    role: "Designer",
    date: "วันจันทร์ ที่ 12 เดือน พฤศจิกายน 2566",
    status: "paused",
    age: "27",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
    grand_total: "$ 7,029,000 3M",
  },
  {
    id: 8,
    name: "Samantha Brooks",
    role: "HR Manager",
    date: "วันจันทร์ ที่ 12 เดือน พฤศจิกายน 2566",
    status: "active",
    age: "31",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
    grand_total: "$ 7,029,000 3M",
  },
  {
    id: 9,
    name: "Frank Harrison",
    role: "F. Manager",
    date: "วันจันทร์ ที่ 12 เดือน พฤศจิกายน 2566",
    status: "vacation",
    age: "33",
    avatar: "https://i.pravatar.cc/150?img=4",
    grand_total: "$ 7,029,000 3M",
  },
  {
    id: 10,
    name: "Emma Adams",
    role: "Ops Manager",
    date: "วันจันทร์ ที่ 12 เดือน พฤศจิกายน 2566",
    status: "active",
    age: "35",
    avatar: "https://i.pravatar.cc/150?img=5",
    grand_total: "$ 7,029,000 3M",
  },
  {
    id: 11,
    name: "Brandon Stevens",
    role: "Jr. Dev",
    date: "วันจันทร์ ที่ 12 เดือน พฤศจิกายน 2566",
    status: "active",
    age: "22",
    avatar: "https://i.pravatar.cc/150?img=8",
    grand_total: "$ 7,029,000 3M",
  },
  {
    id: 12,
    name: "Megan Richards",
    role: "P. Manager",
    date: "วันจันทร์ ที่ 12 เดือน พฤศจิกายน 2566",
    status: "paused",
    age: "28",
    avatar: "https://i.pravatar.cc/150?img=10",
    grand_total: "$ 7,029,000 3M",
  },
  {
    id: 13,
    name: "Oliver Scott",
    role: "S. Manager",
    date: "วันจันทร์ ที่ 12 เดือน พฤศจิกายน 2566",
    status: "active",
    age: "37",
    avatar: "https://i.pravatar.cc/150?img=12",
    grand_total: "$ 7,029,000 3M",
  },
  {
    id: 14,
    name: "Grace Allen",
    role: "M. Specialist",
    date: "วันจันทร์ ที่ 12 เดือน พฤศจิกายน 2566",
    status: "active",
    age: "30",
    avatar: "https://i.pravatar.cc/150?img=16",
    grand_total: "$ 7,029,000 3M",
  },
  {
    id: 15,
    name: "Noah Carter",
    role: "IT Specialist",
    date: "วันจันทร์ ที่ 12 เดือน พฤศจิกายน 2566",
    status: "paused",
    age: "31",
    avatar: "https://i.pravatar.cc/150?img=15",
    grand_total: "$ 7,029,000 3M",
  },
  {
    id: 16,
    name: "Ava Perez",
    role: "Manager",
    date: "วันจันทร์ ที่ 12 เดือน พฤศจิกายน 2566",
    status: "active",
    age: "29",
    avatar: "https://i.pravatar.cc/150?img=20",
    grand_total: "$ 7,029,000 3M",
  },
  {
    id: 17,
    name: "Liam Johnson",
    role: "Data Analyst",
    date: "วันจันทร์ ที่ 12 เดือน พฤศจิกายน 2566",
    status: "active",
    age: "28",
    avatar: "https://i.pravatar.cc/150?img=33",
    grand_total: "$ 7,029,000 3M",
  },
  {
    id: 18,
    name: "Sophia Taylor",
    role: "QA Analyst",
    date: "วันจันทร์ ที่ 12 เดือน พฤศจิกายน 2566",
    status: "active",
    age: "27",
    avatar: "https://i.pravatar.cc/150?img=29",
    grand_total: "$ 7,029,000 3M",
  },
  {
    id: 19,
    name: "Lucas Harris",
    role: "Administrator",
    date: "วันจันทร์ ที่ 12 เดือน พฤศจิกายน 2566",
    status: "paused",
    age: "32",
    avatar: "https://i.pravatar.cc/150?img=50",
    grand_total: "$ 7,029,000 3M",
  },
  {
    id: 20,
    name: "Mia Robinson",
    role: "Coordinator",
    date: "วันจันทร์ ที่ 12 เดือน พฤศจิกายน 2566",
    status: "active",
    age: "26",
    avatar: "https://i.pravatar.cc/150?img=45",
    grand_total: "$ 7,029,000 3M",
  },
];

export {columns, users, statusOptions};
